teamcity_user: "{{user}}"
teamcity_user_home: "/home/{{teamcity_user}}"
teamcity_version: "{{teamcity.version}}"
teamcity_download_path: "{{teamcity_user_home}}/TeamCity-{{teamcity_version}}.tar.gz"
teamcity_installation_directory: "{{teamcity_user_home}}"
teamcity_installation_path: "{{teamcity_installation_directory}}/TeamCity"
teamcity_data_path: "{{teamcity_user_home}}/TeamCityData"
teamcity_download_url: "http://download.jetbrains.com/teamcity/TeamCity-{{ teamcity_version }}.tar.gz"